### ISSUE TITLE
Public API seems to rely on a private type (type hints)

### ISSUE THREAD

**Issue by abravalheri** [frostming/atoml#13]
Hi @frostming, I recently submitted an issue and associated fixing PR to tomlkit. Would you like me to submit it to `atoml` too?

https://github.com/sdispater/tomlkit/issues/130
https://github.com/sdispater/tomlkit/pull/131 

The gist of the problem is the following:

> Unfortunately, it seems to me that both `dumps` and `loads` type signatures depend on what seems to be a private class... This is specially suggested by: 
> 
> https://github.com/frostming/atoml/blob/2c32ef2880088d73ba577f96fa9bbd4fffe94244/atoml/api.py#L21
> 
> Here the class is imported as `_TOMLDocument` which seems to imply that it is an implementation detail, and private.
> 
> The problem arises when trying to use those functions in a type-safe manner, since users are not supposed to import private terms and `TOMLDocument` is not exposed in `__init__.py`...
> 
> Moreover the implementation of `dumps` suggests that the type hint is not accurate, I suppose the correct would be `(Union[TOMLDocument, dict], bool) -> str`?

**Comment by frostming** [comment]
LGTM, please go ahead

**Comment by frostming** [comment]
Closed by #15
