### ISSUE TITLE
Inconsistent `dumps` when replacing existing item with nested table.

### ISSUE THREAD

**Issue by abravalheri** [frostming/atoml#25]
Hello, I am using `atoml` to try editing an existing document while preserving the original comments and formatting as much as possible.
I noticed that when I try to replace an existing item with a more complex entry (e.g. table), the produced TOML document (via `dumps`) does not correspond to the underlying data structure.

The follow is a minimal example to try to reproduce this error:
```python
>>> import atoml
>>> example = """\
... [a]
... x = 1 # comment
... y = 2
... z = 3
... """
>>> doc = atoml.loads(example)
>>> doc
{'a': {'x': 1, 'y': 2, 'z': 3}}
>>> doc['a']['y'] = {'nested': 1}
>>> text = atoml.dumps(doc)
>>> doc  # this is the data-structure what we expect to obtain if parsing the dumped text
{'a': {'x': 1, 'y': {'nested': 1}, 'z': 3}} 
>>> atoml.loads(text)  # here 'z' is wrongly under 'nested'. The correct would be 'z' under 'a'
{'a': {'x': 1, 'y': {'nested': 1, 'z': 3}}}
>>> print(text)
[a]
x = 1 # comment
[a.y]
nested = 1

z = 3

```

Please notice in this example we expect the key `z` to still be under the `a` table, but the `dump`-ed document ends up putting `z` inside the `nested` sub-table, which is inconsistent with the underlying data-structure.

I believe the expected behaviour of `dumps`, after the modification would be producing the following:
```toml
[a]
x = 1 # comment
z = 3
[a.y]
nested = 1
```
or at least
```toml
[a]
x = 1 # comment
y = { nested = 1 }
z = 3
```

I am using Python 3.8.0 and `atoml` 1.0.3 on Ubuntu 18.04.5 LTS.

Please notice the same happens even when using a `Table` instead of a plain dict:
```python
>>> t = atoml.table()
>>> doc['a']['y'] = t
>>> t['nested'] = 1
>>> print(atoml.dumps(doc))
[a]
x = 1 # comment
[a.y]
nested = 1

z = 3

>>> atoml.loads(atoml.dumps(doc))
{'a': {'x': 1, 'y': {'nested': 1, 'z': 3}}}
```

**Comment by frostming** [comment]
Thanks for your reports, all are valid bug reports. I will investigate them when available.

**Comment by abravalheri** [comment]
Thank you very much @frostming!
