### ISSUE TITLE
Invalid `dumps` output when appending to a multiline array

### ISSUE THREAD

**Issue by abravalheri** [frostming/atoml#26]
Hello @frostming, sorry for reaching out again 😝.
I noticed an unexpected output (and invalid TOML syntax) for `dumps`, when trying to append a dict object to an existing multiline array.  Maybe this should also be considered a bug?

Please find bellow the steps to reproduce the error:
```python
>>> import atoml
>>> example = """\
... x = [
... ]
... """
>>> doc = atoml.loads(example)
>>> doc["x"].append({"name": "John Doe", "email": "john@doe.com"})
>>> doc
{'x': [{'name': 'John Doe', 'email': 'john@doe.com'}]}
>>> print(atoml.dumps(doc))
x = [
, name = "John Doe"
email = "john@doe.com"
]
```
Here we can see that the value dumped for `x` does not conform with the TOML syntax. I would expect the output of `dumps` to be similar to the following:
```
x = [
   {name = "John Doe", email = "john@doe.com"}
]
```

Please notice that even when using explicitly `inline_table`, there still will be errors:
```python
>>> doc = atoml.loads(example)
>>> t = atoml.inline_table()
>>> t.append("name", "John Doe")
{'name': 'John Doe'}

>>> t.append("email", "john@doe.com")
{'name': 'John Doe', 'email': 'john@doe.com'}

>>> doc['x'].append(t)
>>> doc
{'x': [{'name': 'John Doe', 'email': 'john@doe.com'}]}
>>> print(atoml.dumps(doc))
x = [
, {name = "John Doe", email = "john@doe.com"}]
```
Here the extra initial `,` will cause problems when parsing the produced string.

I am using Python 3.8.0 and atoml 1.0.3 on Ubuntu 18.04.5 LTS.

**Comment by frostming** [comment]
Preserving the style is a complicated task and the implementation(from upstream tomlkit) is fragile and not robust. There must be more issues to be discovered, thank you for the reports.
