### ISSUE TITLE
New method for array to control the format

### ISSUE THREAD

**Issue by frostming** [frostming/atoml#39]
As discussed in #38, the `array` element is missing a method to manually add comments and whitespace.

## Proposed Solution

- Add a method `Array.raw_append(item_or_whitespace_or_comment)`
- To keep it simple, it only supports appending, i.e. is not possible to insert in the middle.
- No auto-format is enabled in this method
- Perform whitespace merging?

About commas and whitespace, do you want to auto add them when adding an actual value, or leave it to users for control? @abravalheri

**Comment by frostming** [comment]
Thanks for the suggestion, I think I prefer `add_line` now.

**Comment by frostming** [comment]
Only keep `add_line` to replace `raw_append` because it is less likely to produce a syntax error. For example, comments can only appear as the last element of a line. So `add_line` will not accept comments in `items`, and when `trailing_comma` is True, it won't accept whitespace either.

**Comment by abravalheri** [comment]
Thank you very much @frostming! 🎉
